{
    'name': 'Restrict Create Edit',
    'version': '1.0',
    'summary': """ Restrict Create Edit """,
    'description': """ Restrict Create Edit """,
    'author': 'GeoTechnosoft',
    'license': 'AGPL-3',
    'website': 'http://www.geotechnosoft.com',
    'category': '',
    'depends': ['base', 'purchase', 'sale', 'account', 'l10n_in', 'sale_crm', 'purchase_stock', 'crm', 'mrp', 'stock','mail'],
    'data': [
        'views/sale_view.xml',
        'views/purchase_view.xml',
        'views/invoice_view.xml',
        'views/crm_view.xml',
        'views/bom_view.xml',
        'views/mrp_view.xml',
        'views/lot_view.xml',
        'views/picking_view.xml',
        'views/mail_view.xml',
        'views/account_move.xml',
        'views/payment_view.xml',
    ],
    'installable': True,
    'application': True,
}
